export const deviceActionsTypes = {
    FETCH_DEVICES_START: 'FETCH_DEVICES_START',
    FETCH_DEVICES_SUCCESS: 'FETCH_DEVICES_SUCCESS',
    FETCH_DEVICES_FAILED: 'FETCH_DEVICES_FAILED',
    NOTIFY_START: 'NOTIFY_START',
    NOTIFY_SUCCESS: 'NOTIFY_SUCCESS',
    NOTIFY_FAILED: 'NOTIFY_FAILED'
};